### ISSUE TITLE
Error "spawn java ENOENT" when convert html file to pdf

### ISSUE THREAD

**Issue by lhf552004** [ChaosEvoker/html-to-pdf#10]
Dear @ChaosEvoker .
My OS is Win7 64, is possible here to run your module?
Because I found the path syntax is confilct:
[Error: spawn java ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs:
   [ '-jar',
     'C:\\Projects\\Demo\\node_modules\\html-to-pdf/PDFRenderer.jar',
     'C:\\Projects\\Demo\\label.html',
     '/temp/destination.pdf' ] }

**Comment by ChaosEvoker** [comment]
It looks like you might have a permissioning issue. I would try running it using sudo or Run as Administrator. If that doesn't work let me know.

**Comment by lhf552004** [comment]
Hi, I have tried to run my file as Administrator, but the same error,I thinkit's about the OS problem, So I try it in CentOS . The ENOENT error is gone, But there is an exception occured: 
STDOUT: The Stream Handler Factory is already defined. Moving on to convert to PDF.

STDERR: line 4 column 5 - Warning: <meta> lacks "content" attribute

STDERR: InputStream: Doctype given is ""

STDERR: InputStream: Document content looks like HTML 4.01

STDERR: 1 warning, no errors were found!

STDERR: Exception in thread "main" 
STDERR: java.lang.reflect.InvocationTargetException

STDERR: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
STDERR: 
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

STDERR: Caused by: java.lang.ClassCastException: org.xhtmlrenderer.render.BlockBox cannot be cast to org.xhtmlrenderer.newtable.TableBox
	at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:127)
	at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
STDERR: 
	at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
	at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
	at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:46)
	at org.xhtmlrenderer.layout.Layer.paint(Layer.java:314)

STDERR: 	at org.xhtmlrenderer.pdf.ITextRenderer.paintPage(ITextRenderer.java:384)
	at org.xhtmlrenderer.pdf.ITextRenderer.writePDF(ITextRenderer.java:348)
	at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:315)

STDERR: 	at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:246)
	at PDFRenderer.main(PDFRenderer.java:88)

STDERR: 	... 5 more

Woot! Success!
{ process_code: 1 }

**Comment by ChaosEvoker** [comment]
What are the results when you run under this new environment?

**Comment by shujaathaider** [comment]
I am getting the same error in local environment. I am using mac.  It says:

The Stream Handler Factory is already defined. Moving on to convert to PDF.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/w3c/tidy/Tidy
	at PDFRenderer.main(PDFRenderer.java:70)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.w3c.tidy.Tidy
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
